### ISSUE TITLE
TypeError: Argument 1 passed to Cardinity\Method\ResultObjectMapper::map() must be of the type array, null given,

### ISSUE THREAD

**Issue by ragmon** [cardinity/cardinity-sdk-php#18]
When i'm trying to run my code:

```
$client = Client::create([
				'consumerKey' => Yii::$app->params['cardinity_key'],
				'consumerSecret' => Yii::$app->params['cardinity_secret'],
			]);

			$method = new Payment\Create([
				'amount' => (float)$this->amount,
				'currency' => Yii::$app->params['currency_iso'],
				'description' => Yii::$app->params['dealer'] . ' payment',
				'order_id' => (string)$this->order_id,
				'country' => $this->country_code,
				'payment_method' => Payment\Create::CARD,
				'payment_instrument' => [
					'pan' => $this->card_number,
					'exp_year' => (int)$this->expiration_year,
					'exp_month' => (int)$this->expiration_month,
					'cvc' => $this->cvc,
					'holder' => $this->cardholder_name
				],
				'threeds2_data' => [
			        "notification_url" => Url::to(['balance/cardinity-finalize'], true),
					"browser_info" => [
					   "accept_header" => "text/html",
					   "browser_language" => $browser_info['browser_language'] ?? "en-US",
					   "screen_width" => (int)$browser_info['screen_width'] ?? 1920,
					   "screen_height" => (int)$browser_info['screen_height'] ?? 1040,
					   'challenge_window_size' => $browser_info['challenge_window_size'],
					   "user_agent" => $_SERVER['HTTP_USER_AGENT'] ?? "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:21.0) Gecko/20100101 Firefox/21.0",
					   "color_depth" => (int)$browser_info['color_depth'] ?? 24,
					   "time_zone" => (int)$browser_info['time_zone'] ?? -60,
				   ],
    			],
			]);

			try
			{
				$payment = $client->call($method);
			}
			catch (Exception\Declined $exception)
			{
				$this->payment_status = 0;
				return Yii::t('app', 'Your payment has been declined');
			}
			catch (Exception\ValidationFailed $exception)
			{
				$this->payment_status = 0;
				return Yii::t('app', 'Your payment has been declined, check your credentials (validation)');
			}
			catch (Exception\InvalidAttributeValue $exception)
			{
				$this->payment_status = 0;
				return Yii::t('app', 'Your payment has been declined, check your credentials (invalid_attribute)');
			}
			catch (Cardinity\Exception\NotFound $exception) {
				$this->payment_status = 0;
				return Yii::t('app', 'Error during payment: NotFound');
	        }
	        catch (Exception $exception) {
				$this->payment_status = 0;
				return Yii::t('app', 'Error during payment: Unknown exception');
	        }
```

I got this error:

```
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/cardinity/cardinity-sdk-php/src/Http/Guzzle/ClientAdapter.php on line 53. in /app/vendor/yiisoft/yii2/web/Response.php:373
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(346): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException(Object(TypeError))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(TypeError))
#4 {main}
Previous exception:
TypeError: Argument 1 passed to Cardinity\Method\ResultObjectMapper::map() must be of the type array, null given, called in /app/vendor/cardinity/cardinity-sdk-php/src/Http/Guzzle/ExceptionMapper.php on line 85 and defined in /app/vendor/cardinity/cardinity-sdk-php/src/Method/ResultObjectMapper.php:38
Stack trace:
#0 /app/vendor/cardinity/cardinity-sdk-php/src/Http/Guzzle/ExceptionMapper.php(85): Cardinity\Method\ResultObjectMapper->map(NULL, Object(Cardinity\Method\Error))
#1 /app/vendor/cardinity/cardinity-sdk-php/src/Http/Guzzle/ExceptionMapper.php(36): Cardinity\Http\Guzzle\ExceptionMapper->create('Cardinity\\Excep...', Object(GuzzleHttp\Exception\ClientException), Object(Cardinity\Method\Payment\Create))
#2 /app/vendor/cardinity/cardinity-sdk-php/src/Http/Guzzle/ClientAdapter.php(54): Cardinity\Http\Guzzle\ExceptionMapper->get(Object(GuzzleHttp\Exception\ClientException), Object(Cardinity\Method\Payment\Create))
#3 /app/vendor/cardinity/cardinity-sdk-php/src/Client.php(134): Cardinity\Http\Guzzle\ClientAdapter->sendRequest(Object(Cardinity\Method\Payment\Create), 'POST', 'payments', Array)
#4 /app/vendor/cardinity/cardinity-sdk-php/src/Client.php(110): Cardinity\Client->handleRequest(Object(Cardinity\Method\Payment\Create))
#5 /app/frontend/models/Balance.php(669): Cardinity\Client->call(Object(Cardinity\Method\Payment\Create))
#6 /app/frontend/models/Balance.php(359): frontend\models\Balance->payByCardinity()
#7 /app/frontend/controllers/BalanceController.php(108): frontend\models\Balance->externalPayment()
#8 [internal function]: frontend\controllers\BalanceController->actionPay('78655806')
#9 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#11 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('pay', Array)
#12 /app/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('balance/pay', Array)
#13 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 /app/frontend/web/index.php(21): yii\base\Application->run()
#15 {main}
```

I checked why it's happened. And I found this response from cardinity API:
`Client error: `POST https://api.cardinity.com/v1/payments` resulted in a `403 Forbidden` response`

**Comment by shababcardinity** [comment]
This is due to use of "localhost" as either callback or any for of URL. In order to test in development environment either use your ip address (does not have to be public) or use a service like "ngrok".
